# stage 1
FROM python:3.12-slim AS build

WORKDIR /app

#  Ваш код здесь #
COPY . .
RUN pip install --user --no-cache-dir -r requirements.txt

# stage 2
FROM python:3.12-slim

COPY --from=build /root/.local /root/.local
COPY --from=build /app /app

ENV PATH=/root/.local/bin:$PATH

EXPOSE 5000

# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 