# stage 1
FROM python:3.12-slim AS build

#  Ваш код здесь #
COPY . .
RUN pip install --no-cache-dir --user -r requirements.txt

# stage 2
FROM scratch
COPY --from=build / /

# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 